services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: viability-api
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    restart: unless-stopped